import Head from "next/head";
import Post from "../components/Post/Post";
import PostForm from "../components/PostForm/PostForm";

import styles from "../styles/Home.module.scss";

const DUMMY_POST = {
  content:
    "I’m working in Figma trying to design a new website that shows allof my tweets!",
  date: "02/26/2021",
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>My Posts</h1>

        <ul className={styles.posts}>
          <li>
            <Post content={DUMMY_POST.content} date={DUMMY_POST.date} />
          </li>
          <li>
            <Post content={DUMMY_POST.content} date={DUMMY_POST.date} />
          </li>
          <li>
            <Post content={DUMMY_POST.content} date={DUMMY_POST.date} />
          </li>
        </ul>

        <PostForm />
      </main>
    </div>
  );
}
